// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpCoE7WAmx22BYBgk1gKfXeck-KAsBk8',
    appId: '1:416710405161:web:e987d42af76b9b0c52c038',
    messagingSenderId: '416710405161',
    projectId: 'app-quan-ly-van-ban-cds',
    authDomain: 'app-quan-ly-van-ban-cds.firebaseapp.com',
    storageBucket: 'app-quan-ly-van-ban-cds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0MNfh02UZpyZtecSGaZ7rQ4p6yqx4d68',
    appId: '1:416710405161:android:c5d41f9fc0c7c3c552c038',
    messagingSenderId: '416710405161',
    projectId: 'app-quan-ly-van-ban-cds',
    storageBucket: 'app-quan-ly-van-ban-cds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD74SaXlh7RIdJH3-NCaHXh06sG_I2-PvA',
    appId: '1:416710405161:ios:84c2a9e2847e7af652c038',
    messagingSenderId: '416710405161',
    projectId: 'app-quan-ly-van-ban-cds',
    storageBucket: 'app-quan-ly-van-ban-cds.firebasestorage.app',
    iosBundleId: 'com.example.quanLyVanBan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD74SaXlh7RIdJH3-NCaHXh06sG_I2-PvA',
    appId: '1:416710405161:ios:84c2a9e2847e7af652c038',
    messagingSenderId: '416710405161',
    projectId: 'app-quan-ly-van-ban-cds',
    storageBucket: 'app-quan-ly-van-ban-cds.firebasestorage.app',
    iosBundleId: 'com.example.quanLyVanBan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMpCoE7WAmx22BYBgk1gKfXeck-KAsBk8',
    appId: '1:416710405161:web:e569008fee51164e52c038',
    messagingSenderId: '416710405161',
    projectId: 'app-quan-ly-van-ban-cds',
    authDomain: 'app-quan-ly-van-ban-cds.firebaseapp.com',
    storageBucket: 'app-quan-ly-van-ban-cds.firebasestorage.app',
  );
}
